word0 = input('Adjective: ')
word1 = input('Adjective: ')
word2 = input('Noun: ')
word3 = input('Noun: ')
word4 = input('Plural Noun: ')
word5 = input('Type of Game: ')
word6 = input('Plural Noun: ')
word7 = input('Verb ending in "ING": ')
word8 = input('Verb ending in "ING": ')
word9 = input('Plural Noun: ')
word10 = input('Verb ending in "ING": ')
word11 = input('Noun: ')
word12 = input('Plant: ')
word13 = input('Part of the body: ')
word14 = input('Place: ')
word15 = input('Verb ending in "ING": ')
word16 = input('Adjective: ')
word17 = input('Number: ')
word18 = input('Plural Noun: ')

print('A vacation is when you take a trip to some _{}_ place'.format(word0))
print('with your _{}_ family. Usually you go to some place'.format(word1))
print('that is near a/an _{}_ or up on a/an _{}_.'.format(word2, word3))
print('A good vacation place is one where you can ride _{}_'.format(word4))
print('or play _{}_ or go hunting for _{}_ . I like'.format(word5, word6))
print('to spend my time _{}_ or _{}_.'.format(word7, word8))
print('When parents go on a vacation, they spend their time eating')
print('three _{}_ a day, and fathers play golf, and mothers'.format(word9))
print('sit around _{}_. Last summer, my little brother'.format(word10))
print('fell in a/an _{}_ and got poison _{}_ all'.format(word11, word12))
print('over his _{}_. My family is going to go to (the)'.format(word13))
print('_{}_, and I will practice _{}_. Parents'.format(word14, word15))
print('need vacations more than kids because parents are always very')
print('_{}_ and because they have to work _{}_'.format(word16, word17))
print('hours every day all year making enough _{}_ to pay'.format(word18))
print('for the vacation.')
